chore(release): 0.1.2
padok-team/terraform-azurerm-logger pull request #6
Opened 2022-04-01 14:52 UTC by Laudenlaruto

2022-04-01 14:58 UTC, SamyDjemai submitted a review, later dismissed

2022-04-01 14:58 UTC, qprichard submitted a review, later dismissed

2022-04-29 12:39 UTC, qprichard requested changes

2022-04-29 12:39 UTC, qprichard commented on README.md
> +  source = "git@github.com:padok-team/terraform-azurerm-logger.git?ref=v0.2 .0"
C'est quoi cet espace en trop la? 
```suggestion
  source = "git@github.com:padok-team/terraform-azurerm-logger.git?ref=v0.2.0"
```

2022-04-29 12:39 UTC, qprichard commented on main.tf
> +  log_analytics_workspace_id     = try(var.log_analytics_workspace_id,azurerm_log_analytics_workspace.this[0].id)
inutile de faire le try parce que le azurerm_log_analytics_workspace.this[0] existe seulement si var.log_analytics_workspace_id existe 

```
resource "azurerm_log_analytics_workspace" "this" {
  count               = var.log_analytics_workspace_id == null ? 1 : 0
```

```suggestion
  log_analytics_workspace_id     = var.log_analytics_workspace_id
```

2022-04-29 12:39 UTC, qprichard commented on main.tf
> +  log_analytics_workspace_id     = try(var.log_analytics_workspace_id,azurerm_log_analytics_workspace.this[0].id)
same

2022-04-29 12:39 UTC, qprichard commented on outputs.tf
> +  value       = try(var.log_analytics_workspace_id,azurerm_log_analytics_workspace.this[0].id)
same

2022-04-29 12:47 UTC, qprichard approved these changes

2022-04-29 12:51 UTC, SamyDjemai approved these changes

2022-04-29 12:52 UTC, merged